### ISSUE TITLE
Problem with displaying appointment list when there is an appointment rescheduled

### ISSUE THREAD

**Issue by NKay15** [NKay15/SC2002#20]
When the patient reschedule an appointment, the old appointment and the new appointment both appear as rescheduled. Maybe the old appointment should be deleted or not shown to prevent confusion. I think the status of the new appointment should be pending instead of rescheduled

> Hospital Management System (HMS)
> ==============================
> Please login
> Enter your ID (0 to exit): D001 
> Enter password: password
> Logged in successfully.
> 
> -----Doctor Menu-----
> 1. View Patient Medical Records 
> 2. Update Patient Medical Records
> 3. View Personal Schedule 
> 4. Set Availability for Appointments
> 5. Accept or Decline Appointment Requests
> 6. View Upcoming Appointments
> 7. Record Appointment Outcome
> 8. Change Password
> 9. Log out
> -----End of Menu-----
> Enter menu number: 4
> Enter the date (ddmmyyyy): 11112024
> When do you want to work? Input your start time, in hh mm
> 10 00
> Input your end time, in hh mm
> 17 00
> How many breaks would you like to add?
> 1
> Input your break start time, in hh mm
> 12 00
> Input your break end time, in hh mm
> 13 00
> -----Doctor Menu-----
> 1. View Patient Medical Records
> 2. Update Patient Medical Records
> 3. View Personal Schedule
> 4. Set Availability for Appointments
> 5. Accept or Decline Appointment Requests
> 6. View Upcoming Appointments
> 7. Record Appointment Outcome
> 8. Change Password
> 9. Log out
> -----End of Menu-----
> Enter menu number: 9
> Logging out...
> 
> Hospital Management System (HMS)
> ==============================
> Please login
> Enter your ID (0 to exit): P1001
> Enter password: password
> Logged in successfully.
> 
> -----Patient Menu-----
> 1. View Medical Record
> 2. Update Personal Information
> 3. View Available Appointment Slots
> 4. Schedule an Appointment
> 5. Reschedule an Appointment
> 6. Cancel an Appointment
> 7. View Scheduled Appointments
> 8. View Past Appointment Outcome Records
> 9. Change Password
> 10. Log out
> -----End of Menu-----
> Enter menu number: 4
> 1. Dr. John Smith
> 2. Dr. Emily Clarke
> Select Doctor (0 to Exit): 1
> Enter Date in ddmmyyyy (O to Exit): 11112024
> Enter Time in hhmm (O to Exit): 1100
> Successfully scheduled. Waiting for the doctor.
> -----Patient Menu-----
> 1. View Medical Record
> 2. Update Personal Information
> 3. View Available Appointment Slots
> 4. Schedule an Appointment
> 5. Reschedule an Appointment
> 6. Cancel an Appointment
> 7. View Scheduled Appointments
> 8. View Past Appointment Outcome Records
> 9. Change Password
> 10. Log out
> -----End of Menu-----
> Enter menu number: 4
> 1. Dr. John Smith
> 2. Dr. Emily Clarke
> Select Doctor (0 to Exit): 1
> Enter Date in ddmmyyyy (O to Exit): 11112024
> Enter Time in hhmm (O to Exit): 1600
> Successfully scheduled. Waiting for the doctor.
> -----Patient Menu-----
> 1. View Medical Record
> 2. Update Personal Information
> 3. View Available Appointment Slots
> 4. Schedule an Appointment
> 5. Reschedule an Appointment
> 6. Cancel an Appointment
> 7. View Scheduled Appointments
> 8. View Past Appointment Outcome Records
> 9. Change Password
> 10. Log out
> -----End of Menu-----
> Enter menu number: 7
> 1 :
> Doctor ID: D001
> Date: 11/11/2024
> Time Slot: 11:0
> Status:
> Pending
> -------------
> 2 :
> Doctor ID: D001
> Date: 11/11/2024
> Time Slot: 16:0
> Status:
> Pending
> -------------
> -----Patient Menu-----
> 1. View Medical Record
> 2. Update Personal Information
> 3. View Available Appointment Slots
> 4. Schedule an Appointment
> 5. Reschedule an Appointment
> 6. Cancel an Appointment
> 7. View Scheduled Appointments
> 8. View Past Appointment Outcome Records
> 9. Change Password
> 10. Log out
> -----End of Menu-----
> Enter menu number: 10
> Logging out...
> 
> Hospital Management System (HMS)
> ==============================
> Please login
> Enter your ID (0 to exit): D001
> Enter password: password
> Logged in successfully.
> 
> -----Doctor Menu-----
> 1. View Patient Medical Records
> 2. Update Patient Medical Records
> 3. View Personal Schedule
> 4. Set Availability for Appointments
> 5. Accept or Decline Appointment Requests
> 6. View Upcoming Appointments
> 7. Record Appointment Outcome
> 8. Change Password
> 9. Log out
> -----End of Menu-----
> Enter menu number: 5
> -----Request 1-----
> Name of Patient: Alice Brown
> Patient ID: P1001
> Date: 11/11/2024
> Time: 11:00
> -----End of Request 1-----
> 1. Accept
> 2. Decline
> 3. Later
> 1
> Successfully Accepted!
> -----Request 2-----
> Name of Patient: Alice Brown
> Patient ID: P1001
> Date: 11/11/2024
> Time: 16:00
> -----End of Request 2-----
> 1. Accept
> 2. Decline
> 3. Later
> 3
> This request is still in your pending list. Please don't forget to reply later
> -----Doctor Menu-----
> 1. View Patient Medical Records
> 2. Update Patient Medical Records
> 3. View Personal Schedule
> 4. Set Availability for Appointments
> 5. Accept or Decline Appointment Requests
> 6. View Upcoming Appointments
> 7. Record Appointment Outcome
> 8. Change Password
> 9. Log out
> -----End of Menu-----
> Enter menu number: 9
> Logging out...
> 
> Hospital Management System (HMS)
> ==============================
> Please login
> Enter your ID (0 to exit): P1001
> Enter password: password 
> Logged in successfully.
> 
> -----Patient Menu-----
> 1. View Medical Record
> 2. Update Personal Information
> 3. View Available Appointment Slots
> 4. Schedule an Appointment
> 5. Reschedule an Appointment
> 6. Cancel an Appointment
> 7. View Scheduled Appointments
> 8. View Past Appointment Outcome Records
> 9. Change Password
> 10. Log out
> -----End of Menu-----
> Enter menu number: 7
> 1 :
> Doctor ID: D001
> Date: 11/11/2024
> Time Slot: 11:0
> Status: Confirmed
> -------------
> 2 :
> Doctor ID: D001
> Date: 11/11/2024
> Time Slot: 16:0
> Status:
> Pending
> -------------
> -----Patient Menu-----
> 1. View Medical Record
> 2. Update Personal Information
> 3. View Available Appointment Slots
> 4. Schedule an Appointment
> 5. Reschedule an Appointment
> 6. Cancel an Appointment
> 7. View Scheduled Appointments
> 8. View Past Appointment Outcome Records
> 9. Change Password
> 10. Log out
> -----End of Menu-----
> Enter menu number: 5
> Select appointment to reschedule (0 : exit):
> 1 :
> Doctor ID: D001
> Date: 11/11/2024
> Time Slot: 11:0
> Status: Confirmed
> -------------
> 2 :
> Doctor ID: D001
> Date: 11/11/2024
> Time Slot: 16:0
> Status:
> Pending
> -------------
> 1
> Enter Date in ddmmyyyy (O : exit): 11112024
> Enter Time in (O : exit): 1030 
> Successfully scheduled. Waiting for the doctor.
> Appointment has successfully been rescheduled and pending to be approved by the doctor!
> -----Patient Menu-----
> 1. View Medical Record
> 2. Update Personal Information
> 3. View Available Appointment Slots
> 4. Schedule an Appointment
> 5. Reschedule an Appointment
> 6. Cancel an Appointment
> 7. View Scheduled Appointments
> 8. View Past Appointment Outcome Records
> 9. Change Password
> 10. Log out
> -----End of Menu-----
> Enter menu number: 7
> 1 :
> Doctor ID: D001
> Date: 11/11/2024
> Time Slot: 11:0
> Status: Rescheduled
> -------------
> 2 :
> Doctor ID: D001
> Date: 11/11/2024
> Time Slot: 16:0
> Status:
> Pending
> -------------
> 3 :
> Doctor ID: D001
> Date: 11/11/2024
> Time Slot: 10:30
> Status:
> Rescheduled
> -------------
> -----Patient Menu-----
> 1. View Medical Record
> 2. Update Personal Information
> 3. View Available Appointment Slots
> 4. Schedule an Appointment
> 5. Reschedule an Appointment
> 6. Cancel an Appointment
> 7. View Scheduled Appointments
> 8. View Past Appointment Outcome Records
> 9. Change Password
> 10. Log out
> -----End of Menu-----
> Enter menu number:

**Comment by Morilindo** [comment]
this is to prevent confusion:
case 1
when the rescheduled appointment is pending
old appointment: directly cancelled
new appointment: pending
case 2
when the rescheduled appointment is already accepted by doctor
old appointment: turns to rescheduled
new appointment: if declined, the old appointment would be preserved; if accepted, old appointment would be cancelled.

for case 1, i think it's fitted to the description. for case 2, i will try change the new appointment to pending

**Comment by Morilindo** [comment]
c60b62f solved the issue.

**Comment by Morilindo** [comment]
What kinds of cancelled events should be removed from the lists though? currently I would only delete those rescheduled. If it's cancelled without rescheduling, I would still put them on the list.

**Comment by NKay15** [comment]
I think that the appointments that the patient don't need to go for should not be shown when the patient view scheduled appointment. So cancelled, old rescheduled appointments and rejected appointments should not been shown. I think that if may be a bit confusing for the patient when they see it. Whether you want to delete them is up to you.

**Comment by Morilindo** [comment]
> I think that the appointments that the patient don't need to go for should not be shown when the patient view scheduled appointment. So cancelled, old rescheduled appointments and rejected appointments should not been shown. I think that if may be a bit confusing for the patient when they see it. Whether you want to delete them is up to you.

df12237 solved the issue.
