### ISSUE TITLE
2FA

### ISSUE THREAD

**Issue by Rin-chan** [NKay15/SC2002#25]
Adding a feature for 2FA in login

**Comment by Rin-chan** [comment]
https://medium.com/@ihorsokolyk/two-factor-authentication-with-java-and-google-authenticator-9d7ea15ffee6

**Comment by NKay15** [comment]
Unless you want to use text to print a qr code to scan on command line, the best we can do is to manually enter the code on your phone. No external library need to do this which is kinda amazing.

**Comment by Rin-chan** [comment]
Wow you actually finished it. I was planning to scrap the idea cause it was gonna be a pain to demo

**Comment by NKay15** [comment]
[](https://totp.danhersam.com/)

If we are demoing 2FA, use this website. Copy and paste the code here and use the default settings of 6 digit and 30 token period.
