### ISSUE TITLE
Rewrite UserList as file operations

### ISSUE THREAD

**Issue by Rin-chan** [NKay15/SC2002#26]
Remove userlist and CRUD from text file directly

**Comment by Rin-chan** [comment]
Rewrite the entire text file after editing
https://stackoverflow.com/questions/30631668/is-it-possible-to-change-one-line-in-a-txt-file-without-reading-and-writing-the

**Comment by Morilindo** [comment]
> Rewrite the entire text file after editing https://stackoverflow.com/questions/30631668/is-it-possible-to-change-one-line-in-a-txt-file-without-reading-and-writing-the

Is that possible to use `sed` to edit to the target place?

**Comment by Rin-chan** [comment]
> > Rewrite the entire text file after editing https://stackoverflow.com/questions/30631668/is-it-possible-to-change-one-line-in-a-txt-file-without-reading-and-writing-the
> 
> 
> 
> Is that possible to use `sed` to edit to the target place?

Not sure but you can give it a try ig

**Comment by Morilindo** [comment]
> > > Rewrite the entire text file after editing https://stackoverflow.com/questions/30631668/is-it-possible-to-change-one-line-in-a-txt-file-without-reading-and-writing-the
> > 
> > 
> > Is that possible to use `sed` to edit to the target place?
> 
> Not sure but you can give it a try ig

Added some scripts in 54b54e5, but it only works for unix systems..
