### ISSUE TITLE
[Enhancement] Administrators shall be able to track pending appointments.

### ISSUE THREAD

**Issue by Morilindo** [NKay15/SC2002#28]
It seems administrators only handles appointments in appointment list.
Also, please don't use functions under `AppointmentScheduler`, I changed them to `protected`.

The administrator appointment view value shall display all the possible appointments, and choose one to display the window. UUID is for making sure each appointment is identifiable, instead of indexing.

**Comment by NKay15** [comment]
Tested and its working
