### ISSUE TITLE
Appointment Management

### ISSUE THREAD

**Issue by Morilindo** [NKay15/SC2002#4]
appointment management for patients, doctors, and administrators.

**Comment by Morilindo** [comment]
#5

**Comment by NKay15** [comment]
Just a few notes. The Date class does note have the time of the appointment. It is contain in the appointment class. Use getTimeSlot method for that.
Also, should we use this class for the doctors to view their personal schedule and set their availability for
appointments for make another class to handle it.
Thanks a lot for your work.

**Comment by Morilindo** [comment]
> Just a few notes. The Date class does note have the time of the appointment. It is contain in the appointment class. Use getTimeSlot method for that. Also, should we use this class for the doctors to view their personal schedule and set their availability for appointments for make another class to handle it. Thanks a lot for your work.

Noted. I would update it in next pr. Thanks! 
I think it's better to have another class like DoctorScheduleManager. I would implement it next time.

**Comment by Morilindo** [comment]
#7 
I'm confused with the logic of rescheduling action for a patient. Should the existing appointment be cancelled immediately after rescheduling request, or after the doctor approved new appointment?

**Comment by Morilindo** [comment]
#8 
Updated rescheduling action.
